apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gorenel.fullname" . }}-config
  labels:
    {{- include "gorenel.labels" . | nindent 4 }}
data:
  base_domain: {{ .Values.config.baseDomain | quote }}
  log_level: {{ .Values.config.logLevel | quote }}
  retention_days: {{ .Values.config.retentionDays | quote }}
  ml_service_url: "http://{{ include "gorenel.fullname" . }}-ml:5000"
  redis_url: "redis://{{ .Release.Name }}-redis-master:6379"
