app = "gorenel-app"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile.fly"

[[mounts]]
  source = "gorenel_storage"
  destination = "/var/lib/docker"

[http_service]
  internal_port = 4000 # Dashboard port
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = "shared-cpu-4x"
  memory = "8gb" # Further increased for DinD stability
  cpu_kind = "shared"
  cpus = 4
