# TODO [K8S]: ML Servisi için Dockerfile oluştur.
# 1. Base image olarak python:3.11-slim kullan.
# 2. requirements.txt'yi yükle ve install et.
# 3. app.py ve trained_models/ klasörünü container içine kopyala.
# 4. CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]
